### ISSUE TITLE
Outline- Firmware Game Project

### ISSUE THREAD

**Issue by Starnol** [LiterateProgramming/Firmware_game_project#1]
**1. Describes the feature you will add:** 
     - Since this project is something new it will be more about creating instead of adding to an existing project. 
          - Create interactive games to teach Code Chat  
          - Create and Link to a Web page      
**2. Defines which repository/repositories your code will be added to.**
    - Project has been linked to https://github.com/LiterateProgramming/Firmware_game_project.git
**3. Specifies what libraries, languages, and interfaces your code must work with.**
    - Planning to pull from multiple resources and using a mix of HTML, Python, and CSS
    - Our code will have to be able to adapt. By this I mean the interactive part of the game would not only be videos was areas where the player can try out code and be able to test it. The code being used to check the player's answer needs to be able to read it in any it's typed in. 
**4. Details a series of steps you will follow to complete this feature.**
   - Olivia Starts basic html page with a css page
   - Kaitlyn gathers information to input into game and organizes it
   - Together decided on which topics would be covered.
   - Together decided which topics would need videos and divided out the videos
   - Together decided which questions to ask and how to work out the answer divided up that work.
**5. Defines tests to show the feature works correctly.**
   - We will be running it as a web page (how the player would see it) and go through the problems ourselves. 
**6. Outlines goals for scrum 1 and scrum 2. (If by scrum 1 and 2, you mean if other groups pick this up)**
   - Scrum 1
        - Make sure the webpage opens and still works
        - If there are font problems please fix. 
        - Add more topics that may have been missed
        - If there was a way you type a code and its correct but the program is saying it wrong please update
     -Scrum 2
       - Do the same as Scrum 1. 
       - Remember we all right code differently, so testing the Q&A part is a big part of this project 
       - Also add more details. If you don't feel like a video explained something fully then redo the video.
       - Clean it up so its ready for public use.

**Comment by bjones1** [comment]
This is a good start! Clean up the formatting a bit. Also, what game is this? Provide more details on exactly what your game will do / how it will work.

**Comment by Starnol** [comment]
The formatting was clean when I typed it. Not sure what happened when I click on submit. We are working out the layout of it. I figured out how to code a button and a text box in HTML so far. Also have a CSS stylesheet started.

**Comment by Kahjax** [comment]
**1. Describes the feature you will add:**
- Since this project is something new it will be more about creating instead of adding to an existing project.
- Create interactive games to teach Code Chat 
- Create and Link to a Web page  

**2. Defines which repository/repositories your code will be added to.**
- Project has been linked to https://github.com/LiterateProgramming/Firmware_game_project.git

**3. Specifies what libraries, languages, and interfaces your code must work with.**
- Planning to pull from multiple resources and using a mix of HTML, Python, and CSS
- Our code will have to be able to adapt. By this I mean the interactive part of the game would not only be videos was areas where the player can try out code and be able to test it. The code being used to check the player's answer needs to be able to read it in any it's typed in.

**4. Details a series of steps you will follow to complete this feature.**
- Olivia Starts basic html page with a css page 
- Kaitlyn gathers information to input into game and organizes it
- Together decided on which topics would be covered.
- Together decided which questions to ask and how to work out the answer divided up that work.
- This will be a jeopardy game
- Project's end goal: To have a multiplayer feature and keep track of the players score.

**5. Defines tests to show the feature works correctly.**
- We will be running it as a web page (how the player would see it) and go through the problems ourselves.

**6. Outlines goals for scrum 1 and scrum 2.** 

**Scrum 1:**

_What has been done:_
- Public repo was created
- Started 1 html and 1 css file

_What are our blockers:_ 
- Scheduling conflicts 
- Smart Git License
- Computer crash got a new computer
- Smart Git still having a push issue

**Scrum 2:**

_What has been done:_
- Jeopardy page created (introduction page)
- Walkthrough page created

_What are our blockers:_ 
- Push button not operating correctly
- Formats for Jeopardy

**Comment by bjones1** [comment]
Looks good!
